spring:
  application:
    name: Job-Posting-Application
  datasource:
    url: jdbc:postgresql://localhost:5432/jobdemo
    username: gajanan
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    layout: StandaloneLayout
    syntax-highlight:
      theme: material
    path: /swagger-ui.html
    deep-linking: true
    tags-sorter: alpha
    operations-sorter: method




